name: Build site
on:
  workflow_call:
jobs:
  checkout-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  build-site:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: checkout-repo
    steps:
      - name: Setup Deno
        uses: "denoland/setup-deno@v2"
        with:
          deno-version: v2.x
      - name: Setup environment
        run: deno task setup
      - name: Install exiftool
        run: sudo apt-get -y install exiftool
      - name: Build site
        run: deno task build
